### ISSUE TITLE
[BUG] [1.8] DefaultMethodExtension -> NoSuchMethodException (reflection)

### ISSUE THREAD

**Issue by shaburov** [qameta/atlas#104]
openjdk 15 2020-09-15
```java
Caused by: java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles$Lookup.<init>(java.lang.Class,int)
	at java.base/java.lang.Class.getConstructor0(Class.java:3508)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2711)
	at io.qameta.atlas.core.internal.DefaultMethodExtension.invoke(DefaultMethodExtension.java:24)
	at io.qameta.atlas.core.internal.AtlasMethodHandler.invokeWithRetry(AtlasMethodHandler.java:64)
	at io.qameta.atlas.core.internal.AtlasMethodHandler.invoke(AtlasMethodHandler.java:40)
```

```java
    @Override
    public Object invoke(final Object proxy, final MethodInfo methodInfo, final Configuration config) throws Throwable {
        final Class<?> declaringClass = methodInfo.getMethod().getDeclaringClass();
        final Constructor<MethodHandles.Lookup> constructor = MethodHandles.Lookup.class
                .getDeclaredConstructor(Class.class, int.class);
        constructor.setAccessible(true);
        return constructor.newInstance(declaringClass, MethodHandles.Lookup.PRIVATE)
                .unreflectSpecial(methodInfo.getMethod(), declaringClass)
                .bindTo(proxy)
                .invokeWithArguments(methodInfo.getArgs());
    }
```

Problem -> `MethodHandles.Lookup.class.getDeclaredConstructor(Class.class, int.class);`

**Comment by shaburov** [comment]
@kurau pay attention please

**Comment by shaburov** [comment]
Fix for JDK 15
```java
    public Object invoke(final Object proxy, final MethodInfo methodInfo, final Configuration config) throws Throwable {
        return MethodHandles.lookup()
                .unreflectSpecial(methodInfo.getMethod(), methodInfo.getMethod().getDeclaringClass())
                .bindTo(proxy)
                .invokeWithArguments(methodInfo.getArgs());
    }
```

**Comment by vitekes** [comment]
Hi! Is it possible to release a new version? I can make a pull request to fix this bug.
