### ISSUE TITLE
ElementsCollection doesn't work with Appium

### ISSUE THREAD

**Issue by flotnik** [qameta/atlas#78]
Appium 1.12.1
Atlas 1.5

**_When this code invoked:_**
```
@AndroidFindBy(xpath = "//android.widget.TextView[@resource-id='" + pref + "item_title']")
ElementsCollection<AtlasMobileElement> chats();
```
_**The following error occures:**_
**io.qameta.atlas.core.AtlasException: Can't find valid method**
	at io.qameta.atlas.core.util.ReflectionUtils.lambda$getMatchingMethod$4(ReflectionUtils.java:72)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.qameta.atlas.core.util.ReflectionUtils.getMatchingMethod(ReflectionUtils.java:72)
	at io.qameta.atlas.core.internal.TargetMethodInvoker.invoke(TargetMethodInvoker.java:20)
	at io.qameta.atlas.core.internal.AtlasMethodHandler.invokeWithRetry(AtlasMethodHandler.java:64)
	at io.qameta.atlas.core.internal.AtlasMethodHandler.invoke(AtlasMethodHandler.java:41)
	at com.sun.proxy.$Proxy23.chats(Unknown Source)
	at com.company.appium.framework.pages.hubsPage.HubPageSteps.getTopChats(HubPageSteps.java:51)
	at tests.IntegrationTests.CleanAutoGroupChats(IntegrationTests.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by mseremin** [comment]
This is because, compared to the FindBy annotation, there is no find extension for ElementsCollection in annotations for iOS and Android. Atlas always find only one mobile element, but not a collection.
You can use custom extension to search for ElementsCollection of mobile elements:
`
public class AppiumCollectionFindByExtension implements MethodExtension {

    @Override
    public boolean test(final Method method) {
        return method.isAnnotationPresent(IOSCollectionFindBy.class)
                || method.isAnnotationPresent(AndroidCollectionFindBy.class)
                && List.class.isAssignableFrom(method.getReturnType());
    }

    @Override
    public Object invoke(final Object proxy, final MethodInfo methodInfo, final Configuration configuration) {
        assert proxy instanceof SearchContext;

        final Method method = methodInfo.getMethod();
        final Map<String, String> parameters = getParamValues(method, methodInfo.getArgs());
        final AppiumDriver driver = configuration.getContext(AppiumDriverContext.class)
                .orElseThrow(() -> new AtlasException("AppiumDriver is missing")).getValue();

        final By locator;
        if (driver instanceof AndroidDriver) {
            final String xpath = processParamTemplate(method.getAnnotation(AndroidCollectionFindBy.class).xpath(), parameters);
            final String id = processParamTemplate(method.getAnnotation(AndroidCollectionFindBy.class).id(), parameters);
            final String uiAutomator = processParamTemplate(method.getAnnotation(AndroidCollectionFindBy.class).uiAutomator(), parameters);
            locator = getByLocator(
                    new AppiumCollectionFindByExtension.LocatorWrapper(XPATH, xpath),
                    new AppiumCollectionFindByExtension.LocatorWrapper(ID, id),
                    new AppiumCollectionFindByExtension.LocatorWrapper(UIAUTOMATOR, uiAutomator));

        } else if (driver instanceof IOSDriver) {
            final String xpath = processParamTemplate(method.getAnnotation(framework.customAtlas.annotations.IOSCollectionFindBy.class).xpath(), parameters);
            final String id = processParamTemplate(method.getAnnotation(IOSCollectionFindBy.class).id(), parameters);
            final String accessibility = processParamTemplate(method.getAnnotation(IOSCollectionFindBy.class).accessibility(), parameters);
            final String iOSNsPredicate = processParamTemplate(method.getAnnotation(IOSCollectionFindBy.class).iOSNsPredicate(), parameters);
            final String iOSClassChain = processParamTemplate(method.getAnnotation(IOSCollectionFindBy.class).iOSClassChain(), parameters);
            locator = getByLocator(
                    new AppiumCollectionFindByExtension.LocatorWrapper(XPATH, xpath),
                    new AppiumCollectionFindByExtension.LocatorWrapper(ID, id),
                    new AppiumCollectionFindByExtension.LocatorWrapper(ACCESSIBILITY, accessibility),
                    new AppiumCollectionFindByExtension.LocatorWrapper(PREDICATE, iOSNsPredicate),
                    new AppiumCollectionFindByExtension.LocatorWrapper(CHAIN, iOSClassChain));

        } else {
            throw new AtlasException("Can not identified driver");
        }

        final SearchContext searchContext = (SearchContext) proxy;
        final String name = Optional.ofNullable(method.getAnnotation(Name.class))
                .map(Name::value)
                .map(template -> processParamTemplate(template, parameters))
                .orElse(method.getName());

        final LazyTarget elementsTarget = new LazyTarget(name, () -> {
            final List<WebElement> originalElements = searchContext.findElements(locator);
            final Type methodReturnType = ((ParameterizedType) method.getGenericReturnType())
                    .getActualTypeArguments()[0];

            return IntStream.range(0, originalElements.size())
                    .mapToObj(i -> {
                        final WebElement originalElement = originalElements.get(i);
                        final Configuration childConfiguration = configuration.child();
                        final Target target = new HardcodedTarget(listElementName(name, i), originalElement);
                        return new Atlas(childConfiguration)
                                .create(target, (Class<?>) methodReturnType);
                    })
                    .collect(toList());
        });

        final Configuration childConfiguration = configuration.child();
        Optional.ofNullable(methodInfo.getMethod().getAnnotation(Retry.class)).ifPresent(retry -> {
            final Retryer retryer = new DefaultRetryer(retry);
            childConfiguration.registerContext(new RetryerContext(retryer));
        });

        return new Atlas(childConfiguration)
                .create(elementsTarget, method.getReturnType());
    }

    private By getByLocator(final AppiumCollectionFindByExtension.LocatorWrapper... locatorWrappers) {
        return Stream.of(locatorWrappers)
                .filter(AppiumCollectionFindByExtension.LocatorWrapper::isNotEmptyLocator)
                .map(AppiumCollectionFindByExtension.LocatorWrapper::toBy)
                .findFirst()
                .orElseThrow(() -> new AtlasException("No valid locators found"));
    }

    /**
     * Type of locator.
     */
    enum TypeLocator {
        ID, XPATH, ACCESSIBILITY, PREDICATE, CHAIN, UIAUTOMATOR;
    }

    /**
     * Locator's wrapper.
     */
    private static final class LocatorWrapper {
        private final AppiumFindByExtension.TypeLocator type;
        private final String locator;

        LocatorWrapper(final AppiumFindByExtension.TypeLocator type, final String locator) {
            this.type = type;
            this.locator = locator;
        }

        private boolean isNotEmptyLocator() {
            return !this.locator.isEmpty();
        }

        private By toBy() {
            if (XPATH == type) {
                return By.xpath(locator);
            } else if (ID == type) {
                return By.id(locator);
            } else if (PREDICATE == type) {
                return MobileBy.iOSNsPredicateString(locator);
            } else if (ACCESSIBILITY == type) {
                return MobileBy.AccessibilityId(locator);
            } else if (CHAIN == type) {
                return MobileBy.iOSClassChain(locator);
            } else if (UIAUTOMATOR == type) {
                return MobileBy.AndroidUIAutomator(locator);
            }
            else {
                throw new UnsupportedOperationException("Unsupported locator type");
            }
        }
    }

    private String listElementName(final String name, final int position) {
        return String.format("%s [%s]", name, position);
    }

}
`
And, accordingly, the necessary annotations:
`
/**
 * AndroidCollectionFindBy extension marker.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface AndroidCollectionFindBy {
    String id() default "";
    String xpath() default "";
    String uiAutomator() default "";
}
`
`
/**
 * IOSCollectionFindBy extension marker.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface IOSCollectionFindBy {
    String id() default "";
    String xpath() default "";
    String accessibility() default "";
    String iOSNsPredicate() default "";
    String iOSClassChain() default "";
}
`
Use them before ElementsCollection<AtlasMobileElements>

**Comment by flotnik** [comment]
Thanks for the explanation. I will try your solution. Is it possible to implement this in atlas?

**Comment by mseremin** [comment]
> Thanks for the explanation. I will try your solution. Is it possible to implement this in atlas?
Yes. You must add AppiumCollectionFindByExtension when creating an Atlas instance, like this:
`new Atlas(
                new AppiumDriverConfiguration(
                        DriverRunner.getDriver()))
                                                 .extension(new AppiumCollectionFindByExtension());`

**Comment by mseremin** [comment]
Yes. You must add AppiumCollectionFindByExtension when creating an Atlas instance, like this:
new Atlas( new AppiumDriverConfiguration( DriverRunner.getDriver())) .extension(new AppiumCollectionFindByExtension());

**Comment by flotnik** [comment]
Is it possible to install this extension into atlas library? So, all users will have them out of the box.

**Comment by mseremin** [comment]
This is a question for the Atlas developers :)
